package model;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 10 12:06:51 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PsFDNomenclatureImpl
  extends EntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    NomenclatureId,
    ProjId,
    Acronym,
    Meaning,
    Description,
    PsFDProjects;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int NOMENCLATUREID = AttributesEnum.NomenclatureId.index();
  public static final int PROJID = AttributesEnum.ProjId.index();
  public static final int ACRONYM = AttributesEnum.Acronym.index();
  public static final int MEANING = AttributesEnum.Meaning.index();
  public static final int DESCRIPTION = AttributesEnum.Description.index();
  public static final int PSFDPROJECTS = AttributesEnum.PsFDProjects.index();

  /**
   * This is the default constructor (do not remove).
   */
  public PsFDNomenclatureImpl()
  {
  }

  /**
   * Gets the attribute value for NomenclatureId, using the alias name NomenclatureId.
   * @return the value of NomenclatureId
   */
  public Number getNomenclatureId()
  {
    return (Number) getAttributeInternal(NOMENCLATUREID);
  }

  /**
   * Sets <code>value</code> as the attribute value for NomenclatureId.
   * @param value value to set the NomenclatureId
   */
  public void setNomenclatureId(Number value)
  {
    setAttributeInternal(NOMENCLATUREID, value);
  }

  /**
   * Gets the attribute value for ProjId, using the alias name ProjId.
   * @return the value of ProjId
   */
  public Integer getProjId()
  {
    return (Integer) getAttributeInternal(PROJID);
  }

  /**
   * Sets <code>value</code> as the attribute value for ProjId.
   * @param value value to set the ProjId
   */
  public void setProjId(Integer value)
  {
    setAttributeInternal(PROJID, value);
  }

  /**
   * Gets the attribute value for Acronym, using the alias name Acronym.
   * @return the value of Acronym
   */
  public String getAcronym()
  {
    return (String) getAttributeInternal(ACRONYM);
  }

  /**
   * Sets <code>value</code> as the attribute value for Acronym.
   * @param value value to set the Acronym
   */
  public void setAcronym(String value)
  {
    setAttributeInternal(ACRONYM, value);
  }

  /**
   * Gets the attribute value for Meaning, using the alias name Meaning.
   * @return the value of Meaning
   */
  public String getMeaning()
  {
    return (String) getAttributeInternal(MEANING);
  }

  /**
   * Sets <code>value</code> as the attribute value for Meaning.
   * @param value value to set the Meaning
   */
  public void setMeaning(String value)
  {
    setAttributeInternal(MEANING, value);
  }

  /**
   * Gets the attribute value for Description, using the alias name Description.
   * @return the value of Description
   */
  public String getDescription()
  {
    return (String) getAttributeInternal(DESCRIPTION);
  }

  /**
   * Sets <code>value</code> as the attribute value for Description.
   * @param value value to set the Description
   */
  public void setDescription(String value)
  {
    setAttributeInternal(DESCRIPTION, value);
  }

  /**
   * @return the associated entity PsFDProjectsImpl.
   */
  public PsFDProjectsImpl getPsFDProjects()
  {
    return (PsFDProjectsImpl) getAttributeInternal(PSFDPROJECTS);
  }

  /**
   * Sets <code>value</code> as the associated entity PsFDProjectsImpl.
   */
  public void setPsFDProjects(PsFDProjectsImpl value)
  {
    setAttributeInternal(PSFDPROJECTS, value);
  }

  /**
   * @param nomenclatureId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(Number nomenclatureId)
  {
    return new Key(new Object[] { nomenclatureId });
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("model.PsFDNomenclature");
  }

  /**
   * Add attribute defaulting logic in this method.
   * @param attributeList list of attribute names/values to initialize the row
   */
  protected void create(AttributeList attributeList)
  {
    super.create(attributeList);
    setNomenclatureId(getNextSequenceVal("NOMENCLATURE_ID_SEQ"));
  }
  protected Number getNextSequenceVal(String sequenceName)
  {
    SequenceImpl s = new SequenceImpl(sequenceName, getDBTransaction());
    return s.getSequenceNumber();
  }

}

