package model;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 10 11:32:45 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PsFDDistFinalDocImpl
  extends EntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    RecipientId,
    ProjId,
    DocName,
    Title,
    PsFDProjects;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int RECIPIENTID = AttributesEnum.RecipientId.index();
  public static final int PROJID = AttributesEnum.ProjId.index();
  public static final int DOCNAME = AttributesEnum.DocName.index();
  public static final int TITLE = AttributesEnum.Title.index();
  public static final int PSFDPROJECTS = AttributesEnum.PsFDProjects.index();

  /**
   * This is the default constructor (do not remove).
   */
  public PsFDDistFinalDocImpl()
  {
  }

  /**
   * Gets the attribute value for RecipientId, using the alias name RecipientId.
   * @return the value of RecipientId
   */
  public Number getRecipientId()
  {
    return (Number) getAttributeInternal(RECIPIENTID);
  }

  /**
   * Sets <code>value</code> as the attribute value for RecipientId.
   * @param value value to set the RecipientId
   */
  public void setRecipientId(Number value)
  {
    setAttributeInternal(RECIPIENTID, value);
  }

  /**
   * Gets the attribute value for ProjId, using the alias name ProjId.
   * @return the value of ProjId
   */
  public Integer getProjId()
  {
    return (Integer) getAttributeInternal(PROJID);
  }

  /**
   * Sets <code>value</code> as the attribute value for ProjId.
   * @param value value to set the ProjId
   */
  public void setProjId(Integer value)
  {
    setAttributeInternal(PROJID, value);
  }

  /**
   * Gets the attribute value for DocName, using the alias name DocName.
   * @return the value of DocName
   */
  public String getDocName()
  {
    return (String) getAttributeInternal(DOCNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocName.
   * @param value value to set the DocName
   */
  public void setDocName(String value)
  {
    setAttributeInternal(DOCNAME, value);
  }

  /**
   * Gets the attribute value for Title, using the alias name Title.
   * @return the value of Title
   */
  public String getTitle()
  {
    return (String) getAttributeInternal(TITLE);
  }

  /**
   * Sets <code>value</code> as the attribute value for Title.
   * @param value value to set the Title
   */
  public void setTitle(String value)
  {
    setAttributeInternal(TITLE, value);
  }

  /**
   * @return the associated entity PsFDProjectsImpl.
   */
  public PsFDProjectsImpl getPsFDProjects()
  {
    return (PsFDProjectsImpl) getAttributeInternal(PSFDPROJECTS);
  }

  /**
   * Sets <code>value</code> as the associated entity PsFDProjectsImpl.
   */
  public void setPsFDProjects(PsFDProjectsImpl value)
  {
    setAttributeInternal(PSFDPROJECTS, value);
  }

  /**
   * @param recipientId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(Number recipientId)
  {
    return new Key(new Object[] { recipientId });
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("model.PsFDDistFinalDoc");
  }

  /**
   * Add attribute defaulting logic in this method.
   * @param attributeList list of attribute names/values to initialize the row
   */
  protected void create(AttributeList attributeList)
  {
    super.create(attributeList);
    setRecipientId(getNextSequenceVal("RECIPIENT_ID_SEQ"));
  }
  protected Number getNextSequenceVal(String sequenceName)
  {
    SequenceImpl s = new SequenceImpl(sequenceName, getDBTransaction());
    return s.getSequenceNumber();
  }
}

