package model;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 10 11:05:02 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PsFDClosedIssuesImpl
  extends EntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    IssueId,
    ProjId,
    Description,
    Resolution,
    Signoff,
    ClosedDate,
    PsFDProjects;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int ISSUEID = AttributesEnum.IssueId.index();
  public static final int PROJID = AttributesEnum.ProjId.index();
  public static final int DESCRIPTION = AttributesEnum.Description.index();
  public static final int RESOLUTION = AttributesEnum.Resolution.index();
  public static final int SIGNOFF = AttributesEnum.Signoff.index();
  public static final int CLOSEDDATE = AttributesEnum.ClosedDate.index();
  public static final int PSFDPROJECTS = AttributesEnum.PsFDProjects.index();

  /**
   * This is the default constructor (do not remove).
   */
  public PsFDClosedIssuesImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("model.PsFDClosedIssues");
  }

  /**
   * Gets the attribute value for IssueId, using the alias name IssueId.
   * @return the value of IssueId
   */
  public Number getIssueId()
  {
    return (Number) getAttributeInternal(ISSUEID);
  }

  /**
   * Sets <code>value</code> as the attribute value for IssueId.
   * @param value value to set the IssueId
   */
  public void setIssueId(Number value)
  {
    setAttributeInternal(ISSUEID, value);
  }

  /**
   * Gets the attribute value for ProjId, using the alias name ProjId.
   * @return the value of ProjId
   */
  public Integer getProjId()
  {
    return (Integer) getAttributeInternal(PROJID);
  }

  /**
   * Sets <code>value</code> as the attribute value for ProjId.
   * @param value value to set the ProjId
   */
  public void setProjId(Integer value)
  {
    setAttributeInternal(PROJID, value);
  }

  /**
   * Gets the attribute value for Description, using the alias name Description.
   * @return the value of Description
   */
  public String getDescription()
  {
    return (String) getAttributeInternal(DESCRIPTION);
  }

  /**
   * Sets <code>value</code> as the attribute value for Description.
   * @param value value to set the Description
   */
  public void setDescription(String value)
  {
    setAttributeInternal(DESCRIPTION, value);
  }

  /**
   * Gets the attribute value for Resolution, using the alias name Resolution.
   * @return the value of Resolution
   */
  public String getResolution()
  {
    return (String) getAttributeInternal(RESOLUTION);
  }

  /**
   * Sets <code>value</code> as the attribute value for Resolution.
   * @param value value to set the Resolution
   */
  public void setResolution(String value)
  {
    setAttributeInternal(RESOLUTION, value);
  }

  /**
   * Gets the attribute value for Signoff, using the alias name Signoff.
   * @return the value of Signoff
   */
  public String getSignoff()
  {
    return (String) getAttributeInternal(SIGNOFF);
  }

  /**
   * Sets <code>value</code> as the attribute value for Signoff.
   * @param value value to set the Signoff
   */
  public void setSignoff(String value)
  {
    setAttributeInternal(SIGNOFF, value);
  }

  /**
   * Gets the attribute value for ClosedDate, using the alias name ClosedDate.
   * @return the value of ClosedDate
   */
  public Timestamp getClosedDate()
  {
    return (Timestamp) getAttributeInternal(CLOSEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ClosedDate.
   * @param value value to set the ClosedDate
   */
  public void setClosedDate(Timestamp value)
  {
    setAttributeInternal(CLOSEDDATE, value);
  }

  /**
   * @return the associated entity PsFDProjectsImpl.
   */
  public PsFDProjectsImpl getPsFDProjects()
  {
    return (PsFDProjectsImpl) getAttributeInternal(PSFDPROJECTS);
  }

  /**
   * Sets <code>value</code> as the associated entity PsFDProjectsImpl.
   */
  public void setPsFDProjects(PsFDProjectsImpl value)
  {
    setAttributeInternal(PSFDPROJECTS, value);
  }


  /**
   * @param issueId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(Number issueId)
  {
    return new Key(new Object[] { issueId });
  }

  /**
   * Add attribute defaulting logic in this method.
   * @param attributeList list of attribute names/values to initialize the row
   */
  protected void create(AttributeList attributeList)
  {
    super.create(attributeList);
    setIssueId(getNextSequenceVal("CLOSED_ISSUE_ID_SEQ"));
  }
  protected Number getNextSequenceVal(String sequenceName)
  {
    SequenceImpl s = new SequenceImpl(sequenceName, getDBTransaction());
    return s.getSequenceNumber();
  }
}

